Escape Grype failure

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -104,15 +104,22 @@ jobs:
     - name: Install Grype
       run: |
         curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
-
+    
     - name: Scan image with Grype
       run: |
-         grype ${COMPONENT}:latest --fail-on medium -o sarif > grype-report.sarif
+        grype ${{env.COMPONENT}}:latest --fail-on medium -o sarif > grype-report.sarif || echo "GRYPE_FAIL=true" >> "$GITHUB_ENV"
+
     
     - name: Upload Grype scan results to Github Code Scanning
       uses: github/codeql-action/upload-sarif@v2
       with:
         sarif_file: grype-report.sarif
+    
+    - name: Exit if Grype fails
+      run: | 
+        if [ -n "$GRYPE_FAIL" ]; then
+          exit 1 
+        fi
   # Optional: Deploy to container registry
   # Uncomment and configure as needed
   # deploy:
